# Generated by Gomplate at {{ (time.Now).Format time.RFC1123Z }}
XDEBUG_MODE=develop,debug,coverage
TERM='xterm-256color'
FORCE_COLOR=1
ROADRUNNER_CONFIG='.rr.dev.yaml'
MISE_POETRY_AUTO_INSTALL=1
MISE_POETRY_VENV_AUTO=1
BUILD_DIR=.build
