---
# Generated by Gomplate at {{ (time.Now).Format time.RFC1123Z }}
|-
  command -v brew >/dev/null 2>&1 && brew bundle install --quiet;
  dotenv_if_exists '.env.local'
  if command -v mise >/dev/null 2>&1; then eval "$(mise activate zsh --shims)" mise install --quiet 2>/dev/null; fi
  if [[ "${DOCKER_SYNC}" ]]; then bundle install --quiet; docker-sync start; fi
  poetry env activate --quiet
